# Generated by Django 4.2.7 on 2023-12-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount_productscomment_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='products.discount'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='image',
            field=models.ImageField(default=' ', upload_to='product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commentimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comments')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_images', to='products.productscomment')),
            ],
        ),
    ]
