# Generated by Django 4.2.7 on 2023-12-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productversion_discount_productversion_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='products.size'),
        ),
    ]
