# Generated by Django 4.2.7 on 2023-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productversion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
