# Generated by Django 4.2.7 on 2023-12-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productversion_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
