# Generated by Django 4.2.7 on 2023-12-27 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productversion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
